name: Build JavaScript

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: scriptable
      - run: bun run build
        working-directory: scriptable
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[skip ci] Build 'pollen.js'"
          file_pattern: scriptable/pollen.js
