name: Build JavaScript

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-scriptable:
    name: Build (Scriptable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
          cache: "npm"
          cache-dependency-path: scriptable/package-lock.json
      - run: npm ci
        working-directory: scriptable
      - run: npm run build
        working-directory: scriptable
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[skip ci] Build 'pollen.js'"
          file_pattern: scriptable/pollen.js

  build-xbar:
    name: Build (xbar)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
          cache: "npm"
          cache-dependency-path: xbar/package-lock.json
      - run: npm ci
        working-directory: xbar
      - run: npm run build
        working-directory: xbar
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[skip ci] Build 'pollen.5m.js'"
          file_pattern: xbar/pollen.5m.js
