name: Typecheck

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck-scriptable:
    name: Typecheck (Scriptable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
          cache: "npm"
          cache-dependency-path: scriptable/package-lock.json
      - run: npm ci
        working-directory: scriptable
      - run: npm run typecheck
        working-directory: scriptable

  typecheck-xbar:
    name: Typecheck (xbar)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "26"
          cache: "npm"
          cache-dependency-path: xbar/package-lock.json
      - run: npm ci
        working-directory: xbar
      - run: npm run typecheck
        working-directory: xbar
